# Generated by Django 4.0.1 on 2023-12-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0002_alter_clasenatacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasenatacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
