# Generated by Django 4.0.1 on 2023-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USUARIOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
