# Generated by Django 4.0.1 on 2023-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USUARIOS', '0002_alter_customuser_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
